title: Jari's first Jekyll page
author: Jari Oksanen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is awesome description of this first page I did.

# social links
twitter_username: oksanen_jari # DO NOT include the @ character, or else the build will fail!
github_username:  jaroksan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
